spring:
  application:
    name: edge
  config:
    import: optional:classpath:application-secrets.yaml

mqtt:
  broker:
    url: tcp://localhost:1883
  topic: steptrack

dashboard:
  api:
    url: http://localhost:8080
